version: 2
updates:
  - package-ecosystem: pip
    directory: /apps/control_api
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /apps/control_web
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /apps/sandbox_api
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /apps/sandbox_web
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /apps/browser_worker
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /apps/dom_agent
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
