{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flowpilot.serviceAccountName" . }}
  labels:
    {{- include "flowpilot.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
